### ISSUE TITLE
http://localhost:8080/ displays "Petstore" Swagger-UI 

### ISSUE THREAD

**Issue by spencer-forrest-opt** [adriens/imgflip-api#25]
# Problem

I try to access the Swagger for the API.   
According to the [readme.md](https://github.com/ImgFlip-Lovers/imgflip-api#swagger):
>Swagger
>Go to http://localhost:8080/

When I go to http://localhost:8080/, I get redirected to the "Petstore" Swagger-UI - http://localhost:8080/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config:

![Screenshot 2022-08-10 at 16 18 53](https://user-images.githubusercontent.com/104797863/183822130-12657526-3d98-4d5c-96a2-0f36d37e5a25.png)

**Comment by spencer-forrest-opt** [comment]
# Solved
I emptied my web browser cache and it worked.

**Comment by adriens** [comment]
Amazing :eyes: @HakumenNC :muscle:
